---
- name: Check user exists
  user: name=downlink shell=/bin/bash uid=1094 groups=www-data append=yes

- name: Remove symlink
  file: path={{ installdir }} state=absent

- name: Extraction dir exists
  file: path={{ extractdir }} state=directory owner=downlink group=www-data mode=0755

- name: Extract package files
  unarchive: src={{ appname }}-{{ version }}.tbz2 dest={{ extractdir }} owner=downlink group=www-data

- name: Update symlink
  file: path={{ installdir }} state=link src={{ extractdir }}

- name: Install rsyslog config
  template: src=rsyslog.j2 dest=/etc/rsyslog.d/40-{{ appname }}.conf owner=root group=root mode=644
  notify:
    - restart rsyslog

- name: Install logrotate config
  template: src=logrotate.j2 dest=/etc/logrotate.d/{{ appname }} owner=root group=root mode=644

- name: Restart app
  shell: su downlink -c "./stop.sh; ./start.sh"
  args:
    chdir: "{{ installdir }}"

- name: Check static dir exists
  file: path=/opt/static state=directory owner=downlink group=www-data mode=0755

- name: Copy static JS files
  copy: src=../dist/{{ item }} dest=/opt/static/js/{{ item }} owner=downlink group=www-data mode=0644
  with_items:
    - "reveal-sync.js"
    - "socket.io.js"
